version: 2

defaults: &defaults
  working_directory: ~/latex.js
  docker:
    - image: circleci/node:10-stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: apt-get install -y rsync
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build LaTeX.js
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./bin
            - ./dist

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/latex.js

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run unit tests
          command: npm run testc
      - run:
          name: Generate code coverage
          command: npm run cover
          when: always

      - store_artifacts:
          path: test/test-results.xml
          prefix: tests
      - store_artifacts:
          path: test/coverage
          prefix: coverage
      - store_test_results:
          path: test/test-results.xml
          prefix: tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - test:
          requires:
            - build
          filters:
            branches:
              only: /master/
